name: Publish

on:
  workflow_dispatch:
    inputs:
      release-title:
        description: 'Release Title'
        required: false
      mod-version:
        description: 'Mod Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_VERSION: ${{github.ref_name}}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Bump version
        run: VERSION="${{github.events.inputs.mod-version}}" ./.github/scripts/bumpVersion.sh

      - name: Commit version bump
        uses: EndBug/add-and-commit@v7
        with:
          add: ./gradle.properties
          message: ${{ format('[CI] Bump version to {0}', github.events.inputs.mod-version) }}
          branch: main

      - name: Publish to GitHub
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          title: ${{ github.event.inputs.release-title }}

      - name: Publish to CurseForge
        run: |
          chmod +x ./gradlew
          ./gradlew build publish curseforge --stacktrace
        env:
          ORG_GRADLE_PROJECT_curseforgeToken: ${{ secrets.CURSEFORGE_API_KEY }}

      - name: Publish to Modrinth
        run: |
          chmod +x ./gradlew
          ./gradlew build publish modrinth --stacktrace
        env:
          ORG_GRADLE_PROJECT_modrinthToken: ${{ secrets.MODRINTH_API_KEY }}