name: Publish

on:
  workflow_dispatch:
    inputs:
      release-title:
        description: 'Release Title'
        required: false
      mod-version:
        description: 'Mod Version'
        required: true

jobs:
  build-and-bump-version:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.build-and-bump-version.outputs.build }}
    env:
      NEXT_VERSION: ${{github.ref_name}}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Bump version
        run: VERSION="${{github.events.inputs.mod-version}}" ./.github/scripts/bumpVersion.sh

      - name: Commit version bump
        uses: EndBug/add-and-commit@v7
        with:
          add: ./gradle.properties
          message: ${{ format('[CI] Bump version to {0}', github.events.inputs.mod-version) }}
          branch: main

        - name: Publish to CurseForge
            run: |
              chmod +x ./gradlew
              ./gradlew build publish curseforge --stacktrace
            env:
              ORG_GRADLE_PROJECT_curseforgeToken: ${{ secrets.CURSEFORGE_API_KEY }}

        - name: Publish to Modrinth
          run: |
            chmod +x ./gradlew
            ./gradlew build publish modrinth --stacktrace
          env:
            ORG_GRADLE_PROJECT_modrinthToken: ${{ secrets.MODRINTH_API_KEY }}